---
# tasks file for cockpit

- name: Ensure base Cockpit Web Console packages are installed
  package:
    name: "{{ cockpit_base_packages }}"
    state: present
    enablerepo: "{{ cockpit_enablerepo | default(omit, true) }}"

- name: Ensure Cockpit Web Console is started and enabled on boot
  service:
    name: "{{ cockpit_service }}"
    state: started
    enabled: yes

- name: Ensure extra Cockpit Web Console packages are installed
  package:
    name: "{{ cockpit_extra_packages }}"
    state: present
    enablerepo: "{{ cockpit_enablerepo | default(omit, true) }}"
  notify: restart cockpit
  when: cockpit_extra_packages | length > 0
